exp_base: "results/"
exp_name: "dp_dsgt_cifar100_e_10_d_1e-5"
system: "DPDSGTSystem"
gpu_device: 0
num_workers: 0
seed: 1331
data_params:
  data_split_value: 1
  dataset: "cifar100"
graph_params:
  num_nodes: 10
  type: "complete"
  graph: None
  neighbor_weight: "average"
  p: 0.4
  gen_attempts: 100
model: "dpresnet9"
loss: "CrossEntropy"
optim_params:
  batch_size: 50
  learning_rate_start: 0.174
  learning_rate_finish: 0.05
  optimizer: "sgd"
dp_params:
  effective_batch_size: 250
  max_grad_norm: 10
  delta: 0.00001
  epsilon: 10
  noise_multiplier: null
num_iterations: 25000
iterations_per_validate: 250
save_checkpoints_per_iter: null