exp_base: "results/"
exp_name: "dp_central_cifar100_e_10_d_1e-5"
system: "CentralDPSystem"
gpu_device: 0
num_workers: 0
seed: 1331
data_params:
  dataset: "cifar100"
model: "dpresnet9"
loss: "CrossEntropy"
optim_params:
  batch_size: 50
  momentum: 0.9
  weight_decay: 0.0001
  learning_rate_start: 0.05
  learning_rate_finish: 0.01
  optimizer: "sgd"
dp_params:
  effective_batch_size: 250
  max_grad_norm: 1
  delta: 0.00001
  epsilon: 10
  noise_multiplier: null
num_iterations: 25000
iterations_per_validate: 250
save_checkpoints_per_iter: null
