exp_base: "results/"
exp_name: "central_cifar100_sgd_optim"
system: "CentralSystem"
gpu_device: 0
num_workers: 0
seed: 1331
data_params:
  dataset: "cifar100"
model: "dpresnet9"
loss: "CrossEntropy"
optim_params:
  batch_size: 250
  momentum: 0.9
  weight_decay: 0.0001
  learning_rate_start: 0.05
  learning_rate_finish: 0.005
  optimizer: "sgd"
num_iterations: 25000
iterations_per_validate: 250
save_checkpoints_per_iter: null