exp_base: "results/"
exp_name: "no_comms_mnist_10_node_adam_optim"
system: "DistributedSystemNoComms"
gpu_device: 0
num_workers: 0
seed: 1331
data_params:
  data_split_type: "hetero"
  dataset: "mnist"
graph_params:
  num_nodes: 10
  type: "complete"
  p: 0.3
  gen_attempts: 100
model: "convnet"
loss: "CrossEntropy"
optim_params:
  batch_size: 256
  learning_rate_start: 0.005
  learning_rate_finish: 0.0005
  optimizer: "adam"
num_iterations: 2000
iterations_per_validate: 20
save_checkpoints_per_iter: null